_wandb:
    value:
        cli_version: 0.21.1
        code_path: code/modificados/gpi_pd/treina_agente.py
        e:
            tyetz0mlng2romk32gab3flcanva8742:
                args:
                    - gpipd
                    - "30"
                    - "True"
                    - "False"
                codePath: modificados/gpi_pd/treina_agente.py
                codePathLocal: treina_agente.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "1081101176832"
                        used: "34705981440"
                email: pasqualotto.alef@gmail.com
                executable: /home/alef_pasqualotto/]/envs/rllib_gpipd/bin/python
                git:
                    commit: 1ec63450475efc720aca8767c8abf25d876d2c33
                    remote: https://github.com/fredezm/turbo-shower.git
                gpu: NVIDIA GeForce RTX 3060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3060
                      uuid: GPU-0f2b77b8-5c41-c5e9-3473-cf776722fa97
                host: a
                memory:
                    total: "16597204992"
                os: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/alef_pasqualotto/turbo-shower/modificados/gpi_pd/treina_agente.py
                python: CPython 3.10.18
                root: /home/alef_pasqualotto/turbo-shower/modificados/gpi_pd
                startedAt: "2025-08-19T17:38:48.016880Z"
                writerId: tyetz0mlng2romk32gab3flcanva8742
        m:
            - "2": '*'
              "5": 2
              "6":
                - 1
              "7": []
            - "1": global_step
              "6": []
              "7": []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 2
                - 3
                - 30
            "2":
                - 1
                - 2
                - 3
                - 30
            "3":
                - 2
                - 7
                - 13
                - 16
                - 19
            "4": 3.10.18
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
algo:
    value: gpi_pd_Tinf30
alpha:
    value: 0.6
batch_size:
    value: 128
buffer_size:
    value: 400000
delay_policy_update:
    value: 2
dyna:
    value: false
dynamics_min_uncertainty:
    value: 2
dynamics_net_arch:
    value:
        - 200
        - 200
        - 200
        - 200
dynamics_real_ratio:
    value: 0.1
dynamics_rollout_batch_size:
    value: 50000
dynamics_rollout_freq:
    value: 250
dynamics_rollout_len:
    value: 5
dynamics_rollout_starts:
    value: 1000
dynamics_train_freq:
    value: 250
env_id:
    value: Shower-v0
eval_freq:
    value: 1000
eval_mo_freq:
    value: 10000
gamma:
    value: 0.99
gradient_updates:
    value: 20
known_front:
    value: null
learning_rate:
    value: 0.001
learning_starts:
    value: 100
min_priority:
    value: 0.1
net_arch:
    value:
        - 256
        - 256
num_eval_episodes_for_front:
    value: 5
num_eval_weights_for_eval:
    value: 50
num_eval_weights_for_front:
    value: 100
num_q_nets:
    value: 2
per:
    value: true
policy_noise:
    value: 0.2
ref_point:
    value:
        - -20
        - 0
seed:
    value: null
tau:
    value: 0.005
timesteps_per_iter:
    value: 10000
total_timesteps:
    value: 200000
weight_selection_algo:
    value: gpi-ls
